ExpenseAppMvc/Controllers/ExpenseFormController.cs
using ExpenseAppMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpenseAppMvc.Controllers
{
    public class ExpenseFormController : Controller
    {

        Context c = new Context();
        // GET: ExpenseForm
        [Authorize]
        public ActionResult Index()
        {
            var username = (string)Session["Username"];
            var id = c.Users.Where(x => x.Username == username.ToString()).Select(y => y.Id).FirstOrDefault();
            var expenseForms = from x in c.ExpenseForms select x;
            expenseForms = expenseForms.Where(x => x.UserId == id);

            //var degerler = c.ExpenseForms.Where(x => x.UserId == id).Select(y=>y.IsDeleted == true).ToList();
            //return View(degerler);
            return View(expenseForms.ToList());
        }
        public ActionResult RejectReason()
        {
            var username = (string)Session["Username"];
            var id = c.Users.Where(x => x.Username == username.ToString()).Select(y => y.Id).FirstOrDefault();
            var expenseForms = from x in c.ExpenseForms select x;
            expenseForms = expenseForms.Where(x => x.UserId == id);

            //var degerler = c.ExpenseForms.Where(x => x.UserId == id).Select(y=>y.IsDeleted == true).ToList();
            //return View(degerler);
            return View(expenseForms.ToList());
        }

        public ActionResult Onay()
        {
            var username = (string)Session["Username"];
            var id = c.Users.Where(x => x.Username == username.ToString()).Select(y => y.Id).FirstOrDefault();
            var expenseForms = from x in c.ExpenseForms select x;
            expenseForms = expenseForms.Where(x => x.UserId == id);

            return View(expenseForms.ToList());
        }

        public ActionResult Search(string p)
        {
                var expenseForms = from x in c.ExpenseForms select x;
                if (!string.IsNullOrEmpty(p))
                {
                    expenseForms = expenseForms.Where(y => y.Description.Contains(p) || y.RejectReason.Contains(p));
                }
                return View(expenseForms.ToList());
           
        }


        [HttpGet]
        public ActionResult NewExpenseForm()
        {
            List<SelectListItem> value = (from x in c.Currencies.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Code,
                                              Value = x.Id.ToString()
                                          }).ToList();

            List<SelectListItem> uservalue = (from x in c.Users.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.Id.ToString()
                                              }).ToList();

            List<SelectListItem> expenseStatusValue = (from x in c.ExpenseStatuses.ToList()
                                                       select new SelectListItem
                                                       {
                                                           Text = x.Name,
                                                           Value = x.Id.ToString()
                                                       }).ToList();

            ViewBag.newvalue = value;
            ViewBag.newuser = uservalue;
            ViewBag.newExpenseStatusValue = expenseStatusValue;
            return View();
        }
        [HttpPost]
        public ActionResult NewExpenseForm(ExpenseFormHistory expense)
        {
            c.expenseFormHistories.Add(expense);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult NewExpenseFormHistory()
        {
            List<SelectListItem> value = (from x in c.Currencies.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Code,
                                              Value = x.Id.ToString()
                                          }).ToList();

            List<SelectListItem> uservalue = (from x in c.Users.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.Id.ToString()
                                              }).ToList();

            List<SelectListItem> expenseStatusValue = (from x in c.ExpenseStatuses.ToList()
                                                       select new SelectListItem
                                                       {
                                                           Text = x.Name,
                                                           Value = x.Id.ToString()
                                                       }).ToList();

            ViewBag.newvalue = value;
            ViewBag.newuser = uservalue;
            ViewBag.newExpenseStatusValue = expenseStatusValue;
            return View();
        }
        [HttpPost]
        public ActionResult NewExpenseFormHistory(ExpenseFormHistory expense)
        {
            c.expenseFormHistories.Add(expense);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ExpenseFormDelete(int id)
        {
            var value = c.ExpenseForms.Find(id);
            var historyvalue = c.ExpenseHistories.Find(id);
            value.IsDeleted = false;
            historyvalue.IsExpenseDeleted = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ExpenseFormUpdate(int id)
        {
            List<SelectListItem> value = (from x in c.Currencies.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Code,
                                              Value = x.Id.ToString()
                                          }).ToList();

            List<SelectListItem> uservalue = (from x in c.Users.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.Id.ToString()
                                              }).ToList();

            List<SelectListItem> expenseStatusValue = (from x in c.ExpenseStatuses.ToList()
                                                       select new SelectListItem
                                                       {
                                                           Text = x.Name,
                                                           Value = x.Id.ToString()
                                                       }).ToList();
            ViewBag.newvalue = value;
            ViewBag.newuser = uservalue;
            ViewBag.newExpenseStatusValue = expenseStatusValue;
            var expenseFormValue = c.ExpenseForms.Find(id);
            return View("ExpenseFormUpdate", expenseFormValue);
        }

        public ActionResult ExpenseFormInformation(ExpenseForm expenseForm)
        {
            var expenseFormValue = c.ExpenseForms.Find(expenseForm.Id);
            expenseFormValue.Description = expenseForm.Description;
            expenseFormValue.RejectReason = expenseForm.RejectReason;
            expenseFormValue.CreateDate = expenseForm.CreateDate;
            expenseFormValue.IsDeleted = expenseForm.IsDeleted;
            expenseFormValue.CurrencyId = expenseForm.CurrencyId;
            expenseFormValue.ExpenseStatusId = expenseForm.ExpenseStatusId;
            expenseFormValue.UserId = expenseForm.UserId;

            c.SaveChanges();
            return RedirectToAction("Index");
        }

        //public ActionResult ExpenseFormHistoryUpdate(int id)
        //{
        //    List<SelectListItem> value = (from x in c.Currencies.ToList()
        //                                  select new SelectListItem
        //                                  {
        //                                      Text = x.Code,
        //                                      Value = x.Id.ToString()
        //                                  }).ToList();

        //    List<SelectListItem> uservalue = (from x in c.Users.ToList()
        //                                      select new SelectListItem
        //                                      {
        //                                          Text = x.Name,
        //                                          Value = x.Id.ToString()
        //                                      }).ToList();

        //    List<SelectListItem> expenseStatusValue = (from x in c.ExpenseStatuses.ToList()
        //                                               select new SelectListItem
        //                                               {
        //                                                   Text = x.Name,
        //                                                   Value = x.Id.ToString()
        //                                               }).ToList();
        //    ViewBag.newvalue = value;
        //    ViewBag.newuser = uservalue;
        //    ViewBag.newExpenseStatusValue = expenseStatusValue;
        //    var expenseFormValue = c.ExpenseForms.Find(id);
        //    return View("ExpenseFormHistoryUpdate", expenseFormValue);
        //}

ExpenseAppMvc/Views/ExpenseForm/ExpenseFormHistoryInformation.cshtml
@model ExpenseAppMvc.Models.ExpenseFormHistory
@{
    ViewBag.Title = "ExpenseFormHistoryInformation";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>ExpenseFormHistoryInformation</h2>
@using (Html.BeginForm("ExpenseFormInformation", "ExpenseForm", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.ExpenseFormId)
    @Html.TextBoxFor(x => x.ExpenseFormId, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseFormStatusId)

    @Html.DropDownListFor(x => x.ExpenseFormStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.ExpenseFormStatusId, new { @class = "form-control" })*@
    <br />
    @Html.LabelFor(x => x.UserId)
    @*@Html.TextBoxFor(x => x.UserId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.newuser, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ExpenseFormCurrencyId)
    @*@Html.TextBoxFor(x => x.ExpenseFormCurrencyId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.ExpenseFormCurrencyId, (List<SelectListItem>)ViewBag.newvalue, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseFormDescription)
    @Html.TextBoxFor(x => x.ExpenseFormDescription, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseFormDescription)
    @Html.TextBoxFor(x => x.ExpenseFormDescription, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.IsExpenseFormDeleted)
    @Html.TextBoxFor(x => x.IsExpenseFormDeleted, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning" id="updatebtn">UPDATE</button>

    <script>
        $('#btn1').click(function () {
            swal("Expense Forms History Updated!");
        });
    </script>

}

ExpenseAppMvc/Views/ExpenseForm/ExpenseFormHistoryUpdate.cshtml
@model ExpenseAppMvc.Models.ExpenseFormHistory
    ViewBag.Title = "ExpenseFormHistoryUpdate";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>ExpenseFormHistoryUpdate</h2>

@using (Html.BeginForm("ExpenseFormInformation", "ExpenseForm", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.ExpenseFormId)
    @Html.TextBoxFor(x => x.ExpenseFormId, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseFormStatusId)

    @Html.DropDownListFor(x => x.ExpenseFormStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.ExpenseFormStatusId, new { @class = "form-control" })*@
    <br />
    @Html.LabelFor(x => x.UserId)
    @*@Html.TextBoxFor(x => x.UserId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.newuser, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ExpenseFormCurrencyId)
    @*@Html.TextBoxFor(x => x.ExpenseFormCurrencyId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.ExpenseFormCurrencyId, (List<SelectListItem>)ViewBag.newvalue, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseFormDescription)
    @Html.TextBoxFor(x => x.ExpenseFormDescription, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseFormDescription)
    @Html.TextBoxFor(x => x.ExpenseFormDescription, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.IsExpenseFormDeleted)
    @Html.TextBoxFor(x => x.IsExpenseFormDeleted, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning" id="updatebtn">UPDATE</button>

    <script>
        $('#btn1').click(function () {
            swal("Expense Forms History Updated!");
        });
    </script>

}

ExpenseAppMvc/Views/ExpenseForm/ExpenseFormInformation.cshtml
@model ExpenseAppMvc.Models.ExpenseForm
@{
    ViewBag.Title = "ExpenseFormInformation";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>ExpenseFormInformation</h2>

@using (Html.BeginForm("ExpenseFormInformation", "ExpenseForm", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.Id)
    @Html.LabelFor(x => x.UserId)
    @Html.TextBoxFor(x => x.UserId, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CurrencyId)
    @Html.TextBoxFor(x => x.CurrencyId, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseStatusId)
    @Html.TextBoxFor(x => x.ExpenseStatusId, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Description)
    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.RejectReason)
    @Html.TextBoxFor(x => x.RejectReason, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.IsDeleted)
    @Html.TextBoxFor(x => x.IsDeleted, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Update</button>

}

ExpenseAppMvc/Views/ExpenseForm/ExpenseFormUpdate.cshtml
@model ExpenseAppMvc.Models.ExpenseForm
@{
    ViewBag.Title = "ExpenseFormUpdate";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

<h2>ExpenseFormUpdate</h2>

@using (Html.BeginForm("ExpenseFormInformation", "ExpenseForm", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.Id)

    @Html.LabelFor(x => x.UserId)
    @*@Html.TextBoxFor(x => x.UserId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.newuser, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CurrencyId)
    @*@Html.TextBoxFor(x => x.CurrencyId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.CurrencyId, (List<SelectListItem>)ViewBag.newvalue, new
        { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseStatusId)
    @*@Html.TextBoxFor(x => x.ExpenseStatusId, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.ExpenseStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.IsDeleted)
    @Html.TextBoxFor(x => x.IsDeleted, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Description)
    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.RejectReason)
    @Html.TextBoxFor(x => x.RejectReason, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning" id="updatebtn">UPDATE</button>

    <script>
        $('#btn1').click(function () {
            swal("Expense Forms Updated!");
        });
    </script>

}

ExpenseAppMvc/Views/ExpenseForm/Index.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<br />
@using (Html.BeginForm("Search", "ExpenseForm", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />

<table class="table table-bordered">
    <tr>
        <th>Expense Form Id</th>
        <th>Description</th>
        @*<th>Reason</th>*@
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Delete</th>
        <th>Update</th>
        <th>Approval</th>
        <th>History</th>
    </tr>

    @foreach (var e in Model)
    {
        if (e.IsDeleted == true && e.ExpenseStatusId == 2 && e.RejectReason == null)
        {
            <tr>
                <td>@e.Id</td>
                <td>@e.Description</td>
                @*<td>@e.RejectReason</td>*@
                <td>@e.CreateDate</td>
                <td>@e.Currency.Code</td>
                @*<td>@e.CurrencyId</td>*@
                @*<td>@e.ExpenseStatusId</td>*@
                <td>@e.ExpenseStatus.Name</td>
                @*<td>@e.UserId</td>*@
                <td>@e.User.Name</td>
                <td>
                    <a href="/ExpenseForm/ExpenseFormDelete/@e.Id" id="btn2" class="btn btn-danger">Delete</a>
                </td>
                <td>
                    <a href="/ExpenseForm/ExpenseFormUpdate/@e.Id" class="btn btn-success">Update</a>
                </td>
                <td>
                    <a href="/ExpenseForm/ApprovalProcess/@e.Id" class="btn btn-success">Approval</a>
                </td>
                <td>
                    <a href="/ExpenseForm/NewExpenseFormHistory/" class="btn btn-success">History</a>
                </td>

            </tr>
        }

    }
</table>
<a href="/ExpenseForm/NewExpenseForm/" class="btn btn-success">New ExpenseForm</a>

<script>
    $('#btn2').click(function () {
        swal("Expense Forms Deleted!");
    });
</script>

ExpenseAppMvc/Views/ExpenseForm/NewExpenseForm.cshtml
@model ExpenseAppMvc.Models.ExpenseForm
@*@model Tuple<ExpenseAppMvc.Models.ExpenseForm, ExpenseAppMvc.Models.ExpenseFormHistory>*@
@{
    ViewBag.Title = "NewExpenseForm";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>


    <h2>NewExpenseForm</h2>
    <form class="form-group" method="post">
        @Html.LabelFor(x => x.UserId)
        @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.newuser, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.CurrencyId)
        @Html.DropDownListFor(x => x.CurrencyId, (List<SelectListItem>)ViewBag.newvalue, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.ExpenseStatusId)
        @Html.DropDownListFor(x => x.ExpenseStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.RejectReason)
        @Html.TextBoxFor(x => x.RejectReason, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.CreateDate)
        @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.IsDeleted)
        @Html.TextBoxFor(x => x.IsDeleted, new { @class = "form-control" })
        <br />

        <button class="btn btn-primary" id="btn1">Add</button>

        <script>
            $('#btn1').click(function () {
                swal("Expense Forms Added!");
            });
        </script>
    </form>

@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

<form class="form-group" method="post">
    @Html.LabelFor(x => x.Item1.UserId)
    @Html.DropDownListFor(x => x.Item1.UserId, (List<SelectListItem>)ViewBag.newuser, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Item1.CurrencyId)
    @Html.DropDownListFor(x => x.Item1.CurrencyId, (List<SelectListItem>)ViewBag.newvalue, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Item1.ExpenseStatusId)
    @Html.DropDownListFor(x => x.Item1.ExpenseStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Description)
    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.RejectReason)
    @Html.TextBoxFor(x => x.RejectReason, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.IsDeleted)
    @Html.TextBoxFor(x => x.IsDeleted, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary" id="btn1">Add</button>

    <script>
        $('#btn1').click(function () {
            swal("Expense Forms Added!");
        });
    </script>
</form>*@

ExpenseAppMvc/Views/ExpenseForm/Onay.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<br />
@using (Html.BeginForm("Search", "ExpenseForm", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />

<table class="table table-bordered">
    <tr>
        <th>Description</th>
        <th>Reason</th>
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Delete</th>
        <th>Update</th>
    </tr>

    @foreach (var e in Model)
    {
        if (e.IsDeleted == true)
        {
            <tr>
                <td>@e.Description</td>
                <td>@e.RejectReason</td>
                <td>@e.CreateDate</td>
                <td>@e.Currency.Code</td>
                @*<td>@e.CurrencyId</td>*@
                @*<td>@e.ExpenseStatusId</td>*@
                <td>@e.ExpenseStatus.Name</td>
                @*<td>@e.UserId</td>*@
                <td>@e.User.Name</td>
                <td>
                    <a href="/ExpenseForm/ExpenseFormDelete/@e.Id" id="btn2" class="btn btn-danger">Delete</a>
                </td>
                <td>
                    <a href="/ExpenseForm/ExpenseFormUpdate/@e.Id" class="btn btn-success">Update</a>
                </td>

            </tr>
        }

    }
</table>
<a href="/ExpenseForm/NewExpenseForm/" class="btn btn-success">New ExpenseForm</a>

<script>
    $('#btn2').click(function () {
        swal("Expense Forms Deleted!");
    });
</script>

ExpenseAppMvc/Views/ExpenseForm/RejectReason.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<br />
@using (Html.BeginForm("Search", "ExpenseForm", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />

<table class="table table-bordered">
    <tr>
        <th>Description</th>
        <th>Reason</th>
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Delete</th>
        <th>Update</th>
    </tr>

    @foreach (var e in Model)
    {
        if (e.IsDeleted == true && e.ExpenseStatusId == 2 && e.RejectReason != null)
        {
            <tr>
                <td>@e.Description</td>
                <td>@e.RejectReason</td>
                <td>@e.CreateDate</td>
                <td>@e.Currency.Code</td>
                @*<td>@e.CurrencyId</td>*@
                @*<td>@e.ExpenseStatusId</td>*@
                <td>@e.ExpenseStatus.Name</td>
                @*<td>@e.UserId</td>*@
                <td>@e.User.Name</td>
                <td>
                    <a href="/ExpenseForm/ExpenseFormDelete/@e.Id" id="btn2" class="btn btn-danger">Delete</a>
                </td>
                <td>
                    <a href="/ExpenseForm/ExpenseFormUpdate/@e.Id" class="btn btn-success">Update</a>
                </td>
                <td>
                    <a href="/ExpenseForm/ApprovalProcess/@e.Id" class="btn btn-success">Approval</a>
                </td>

            </tr>
        }

    }
</table>
<a href="/ExpenseForm/NewExpenseForm/" class="btn btn-success">New ExpenseForm</a>

<script>
    $('#btn2').click(function () {
        swal("Expense Forms Deleted!");
    });
</script>