ExpenseAppMvc/Controllers/AccountantController.cs
using ExpenseAppMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpenseAppMvc.Controllers
{
    public class AccountantController : Controller
    {
        Context c = new Context();
        // GET: Accountant
        public ActionResult Index()
        {
            // var expenseForms = c.ExpenseForms.Where(x=> x.IsDeleted == true).ToList();
            var expenseForms = c.ExpenseForms.Where(x => x.ExpenseStatusId == 1).ToList();
            return View(expenseForms.ToList());
        }
        public ActionResult Search(string p)
        {
            var expenseForms = from x in c.ExpenseForms select x;
            if (!string.IsNullOrEmpty(p))
            {
                expenseForms = expenseForms.Where(y => y.Description.Contains(p) || y.RejectReason.Contains(p));
            }
            return View(expenseForms.ToList());
        }

        public ActionResult Payment(int id)
        {
            List<SelectListItem> value = (from x in c.Currencies.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Code,
                                              Value = x.Id.ToString()
                                          }).ToList();

            List<SelectListItem> uservalue = (from x in c.Users.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.Id.ToString()
                                              }).ToList();

            List<SelectListItem> expenseStatusValue = (from x in c.ExpenseStatuses.ToList()
                                                       select new SelectListItem
                                                       {
                                                           Text = x.Name,
                                                           Value = x.Id.ToString()
                                                       }).ToList();
            ViewBag.newvalue = value;
            ViewBag.newuser = uservalue;
            ViewBag.newExpenseStatusValue = expenseStatusValue;
            var expenseFormValue = c.ExpenseForms.Find(id);
            return View("Payment", expenseFormValue);
        }

        public ActionResult PaymentProcess(int id)
        {
            var value = c.ExpenseForms.Find(id);
            value.ExpenseStatusId = 3;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ExpenseAppMvc/Views/Accountant/Index.cshtml
@using ExpenseAppMvc.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AccountantLayout.cshtml";
}
<br />
@using (Html.BeginForm("Search", "Accountant", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>Description</th>
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Payment</th>
    </tr>

    @foreach (var e in Model)
    {
        <tr>
            <td>@e.Description</td>
            <td>@e.CreateDate</td>
            <td>@e.Currency.Code</td>
            <td>@e.ExpenseStatus.Name</td>
            @*<td>@e.UserId</td>*@
            <td>@e.User.Name</td>
            <td>
                <a href="/Accountant/PaymentProcess/@e.Id" class="btn btn-success">Payment</a>
            </td>
        </tr>
    }
</table>

ExpenseAppMvc/Views/Accountant/Payment.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/AccountantLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

@using (Html.BeginForm("Payment", "Accountant", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.UserId)
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.newuser, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CurrencyId)
    @Html.DropDownListFor(x => x.CurrencyId, (List<SelectListItem>)ViewBag.newvalue, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseStatusId)
    @Html.DropDownListFor(x => x.ExpenseStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Description)
    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.RejectReason)
    @Html.TextBoxFor(x => x.RejectReason, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning" id="payment">Payment</button>
    <script>
        $('#payment').click(function () {
            swal("Expense Forms Payment!");
        });
    </script>
}

ExpenseAppMvc/Views/Accountant/Search.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/AccountantLayout.cshtml";
}

<h2>Search</h2>
<br />
@using (Html.BeginForm("Search", "Accountant", FormMethod.Get))
{
    <p>
        Description  @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Description</th>
        <th>Reason</th>
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Delete</th>
        <th>Update</th>
        <th>Detail</th>
    </tr>

    @foreach (var e in Model)
    {
        <tr>
            <td>@e.Description</td>
            <td>@e.RejectReason</td>
            <td>@e.CreateDate</td>
            <td>@e.Currency.Code</td>
            @*<td>@e.CurrencyId</td>*@
            @*<td>@e.ExpenseStatusId</td>*@
            <td>@e.ExpenseStatus.Name</td>
            @*<td>@e.UserId</td>*@
            <td>@e.User.Name</td>
            <td>
                <a href="/ExpenseForm/ExpenseFormDelete/@e.Id" class="btn btn-danger">Delete</a>
            </td>
            <td>
                <a href="/ExpenseForm/ExpenseFormUpdate/@e.Id" class="btn btn-success">Update</a>
            </td>
            <td>
                <a href="/ExpenseForm/ApprovalProcess/@e.Id" id="detail" class="btn btn-outline-primary">Onay</a>
            </td>

        </tr>
    }
</table>