ExpenseAppMvc/Controllers/ExpenseController.cs
using ExpenseAppMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpenseAppMvc.Controllers
{
    public class ExpenseController : Controller
    {
        Context c = new Context();
        // GET: Expense
        public ActionResult Index()
        {
            var expense = c.Expenses.Where(x => x.IsDeleted == true).ToList();
            var toplam = c.Expenses.Where(x => x.ExpenseFormId == x.ExpenseFormId && x.IsDeleted == true).Sum(x => x.Amount);
            ViewBag.toplam = "Toplam tutar: " + toplam;

            return View(expense);
        }
        public ActionResult Search(string p)
        {
            var expenses = from x in c.Expenses select x;
            if (!string.IsNullOrEmpty(p))
            {
                //.Where(y => y.Description.Contains(p));
                expenses = expenses.Where(y => y.Description.Contains(p));
            }
            return View(expenses.ToList());
        }

        [HttpGet]
        public ActionResult NewExpense()
        {
            List<SelectListItem> value = (from x in c.ExpenseForms.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Description,
                                              Value = x.Id.ToString()
                                          }).ToList();
            ViewBag.valueDescription = value;

            return View();
        }
        [HttpPost]
        public ActionResult NewExpense(Expense expense, ExpenseHistory expenseHistory)
        {
            c.Expenses.Add(expense);
            c.SaveChanges();

            c.ExpenseHistories.Add(expenseHistory);
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult NewExpenseHistory()
        {
            List<SelectListItem> value = (from x in c.ExpenseHistories.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.ExpenseDescription,
                                              Value = x.Id.ToString()
                                          }).ToList();
            ViewBag.valueDescription = value;

            return View();
        }
        [HttpPost]
        public ActionResult NewExpenseHistory(ExpenseHistory expenseHistory)
        {
            c.ExpenseHistories.Add(expenseHistory);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteExpense(int id)
        {
            var value = c.Expenses.Find(id);
            value.IsDeleted = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ExpenseGetir(int id)
        {
            List<SelectListItem> value = (from x in c.ExpenseForms.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Description,
                                              Value = x.Id.ToString()
                                          }).ToList();
            ViewBag.valueDescription = value;

            var formvalue = c.Expenses.Find(id);
            return View("ExpenseGetir", formvalue);
        }
        public ActionResult ExpenseUpdate(Expense expense)
        {
            var updateExpense = c.Expenses.Find(expense.Id);
            updateExpense.Description = expense.Description;
            updateExpense.Amount = expense.Amount;
            updateExpense.CreateDate = expense.CreateDate;
            updateExpense.IsDeleted = expense.IsDeleted;
            updateExpense.ExpenseFormId = expense.ExpenseFormId;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ExpenseAppMvc/Controllers/ManagerController.cs
using ExpenseAppMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpenseAppMvc.Controllers
{
    public class ManagerController : Controller
    {

        Context c = new Context();
        // GET: Manager
        [Authorize]
        public ActionResult Index()
        {
            ///-------------------
            //var expenseForms = c.ExpenseForms.Where(x => x.ExpenseStatusId == 2).ToList();
            //return View(expenseForms.ToList());

            //var degerler = c.ExpenseForms.Where(x => x.UserId == id).ToList();

            var username = (string)Session["Username"];
            var id = c.Users.Where(x => x.Username == username.ToString()).Select(y => y.Id).FirstOrDefault();
            var employee = c.Users.Where(x => x.ManagerId == id).Select(y => y.Id).FirstOrDefault();
            var degerler = c.ExpenseForms.Where(x => x.UserId == employee).ToList();
            return View(degerler);


            //var username = (string)Session["Username"];
            //var id = c.Users.Where(x => x.Username == username.ToString()).Select(y => y.Id).FirstOrDefault();
            //var employee = c.Users.Where(x => x.ManagerId == id).Select(y => y.Id).ToList();
            //var degerler = c.ExpenseForms.Where(x => x.UserId == employee).ToList();
            //return View(degerler);

            //var username = (string)Session["Username"];
            //var id = c.Users.Where(x => x.Username == username.ToString()).Select(y => y.Id).FirstOrDefault();
            //var employee = c.Users.Where(x => x.ManagerId == id).Select(y => y.Id).ToString();
            //var degerler = c.ExpenseForms.Where(x => x.Id == employee).ToList();
            //return View(degerler);
        }

        public ActionResult Details(int id)
        {
            var value = c.ExpenseForms.Find(id);
            var expense = c.Expenses.Where(x => x.ExpenseFormId == id).ToList();
            return View(expense);
        }

        public ActionResult Search(string p)
        {
            var expenseForms = from x in c.ExpenseForms select x;
            if (!string.IsNullOrEmpty(p))
            {
                expenseForms = expenseForms.Where(y => y.Description.Contains(p) || y.RejectReason.Contains(p));
            }
            return View(expenseForms.ToList());
        }

        public ActionResult RejectReason(int id)
        {
            List<SelectListItem> value = (from x in c.Currencies.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Code,
                                              Value = x.Id.ToString()
                                          }).ToList();

            List<SelectListItem> uservalue = (from x in c.Users.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.Id.ToString()
                                              }).ToList();

            List<SelectListItem> expenseStatusValue = (from x in c.ExpenseStatuses.ToList()
                                                       select new SelectListItem
                                                       {
                                                           Text = x.Name,
                                                           Value = x.Id.ToString()
                                                       }).ToList();
            ViewBag.newvalue = value;
            ViewBag.newuser = uservalue;
            ViewBag.newExpenseStatusValue = expenseStatusValue;
            var expenseFormValue = c.ExpenseForms.Find(id);
            return View("RejectReason", expenseFormValue);
        }
    }
}

ExpenseAppMvc/Views/Manager/Details.cshtml
@using ExpenseAppMvc.Models;
@model List<Expense>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/ManagerLayout.cshtml";
}

<br />
@using (Html.BeginForm("Search", "Expense", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Create Date</th>
        <th>Expense Form Description</th>
    </tr>
    @foreach (var e in Model)
    {
        if (e.IsDeleted == true)
        {
            <tr>

                <td>@e.Id</td>
                <td>@e.Description</td>
                <td>@e.Amount</td>
                <td>@e.CreateDate</td>
                <td>@e.ExpenseForm.Description</td>

            </tr>
        }
    }
</table>
<br />
@*<div class="container">
    @ViewBag.toplam
</div>*@
<br />
<a href="/Manager/Index/" class="btn btn-info">Expense Forms</a>

ExpenseAppMvc/Views/Manager/Index.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/ManagerLayout.cshtml";
}
<br />
@using (Html.BeginForm("Search", "Manager", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Search" placeholder="Aranacak Kelime Giriniz" />
    </p>
}
<br />

<table class="table table-bordered">
    <tr>
        <th>Description</th>
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Reject Reason</th>
        <th>Details</th>
    </tr>

    @foreach (var e in Model)
    {
        if (e.ExpenseStatusId == 2)
        {
<tr>
    <td>@e.Description</td>
    <td>@e.CreateDate</td>
    <td>@e.Currency.Code</td>
    <td>@e.ExpenseStatus.Name</td>
    @*<td>@e.UserId</td>*@
    <td>@e.User.Name</td>
    <td>
        <a href="/Manager/RejectReason/@e.Id" class="btn btn-success">Reject Reason</a>
    </td>
    <td>
        <a href="/Manager/Details/@e.Id" class="btn btn-success">Details</a>
    </td>
</tr>
        }

    }
</table>

ExpenseAppMvc/Views/Manager/RejectReason.cshtml
@model ExpenseAppMvc.Models.ExpenseForm
@{
    ViewBag.Title = "RejectReason";
    Layout = "~/Views/Shared/ManagerLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

@using (Html.BeginForm("ExpenseFormInformation", "ExpenseForm", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.UserId)
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.newuser, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CurrencyId)
    @Html.DropDownListFor(x => x.CurrencyId, (List<SelectListItem>)ViewBag.newvalue, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ExpenseStatusId)
    @Html.DropDownListFor(x => x.ExpenseStatusId, (List<SelectListItem>)ViewBag.newExpenseStatusValue, new
       { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Description)
    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.RejectReason)
    @Html.TextBoxFor(x => x.RejectReason, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.CreateDate)
    @Html.TextBoxFor(x => x.CreateDate, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning" id="rejectReason">UPDATE</button>

    <script>
        $('#rejectReason').click(function () {
            swal("Reject Reason Added!");
        });
    </script>

}

ExpenseAppMvc/Views/Manager/Search.cshtml
@using ExpenseAppMvc.Models
@model List<ExpenseForm>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/ManagerLayout.cshtml";
}

<h2>Search</h2>

@using (Html.BeginForm("Index", "Manager", FormMethod.Get))
{
    <p>
        Description  @Html.TextBox("p")
        <input type="submit" value="Search" />
    </p>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Description</th>
        <th>Reason</th>
        <th>Create Date</th>
        <th>Currency </th>
        <th>Expense</th>
        <th>User </th>
        <th>Delete</th>
        <th>Update</th>
        <th>Detail</th>
    </tr>

    @foreach (var e in Model)
    {
        <tr>
            <td>@e.Description</td>
            <td>@e.RejectReason</td>
            <td>@e.CreateDate</td>
            <td>@e.Currency.Code</td>
            @*<td>@e.CurrencyId</td>*@
            @*<td>@e.ExpenseStatusId</td>*@
            <td>@e.ExpenseStatus.Name</td>
            @*<td>@e.UserId</td>*@
            <td>@e.User.Name</td>
            <td>
                <a href="/ExpenseForm/ExpenseFormDelete/@e.Id" class="btn btn-danger">Delete</a>
            </td>
            <td>
                <a href="/ExpenseForm/ExpenseFormUpdate/@e.Id" class="btn btn-success">Update</a>
            </td>
            <td>
                <a href="/ExpenseForm/ApprovalProcess/@e.Id" id="detail" class="btn btn-outline-primary">Onay</a>
            </td>

        </tr>
    }
</table>